config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links
  resources :views, path: :snips, only: [:show]
  resources :stats, only: [:index]

  root "links#index"

  get '/about', to: 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user, optional: true
    has_many :views, dependent: :destroy
    scope :recent_first, -> { order(created_at: :desc) }
    validates :url, presence: true
    validate :url_format, if: -> { url.present? }
    validate :url_exists, if: -> { url.present? }

    after_save_commit if: :url_previously_changed? do
        MetadataJob.perform_async(to_param)
    end 

    def self.find(id)
        super ShortCode.decode(id)
    end

    def to_param
        ShortCode.encode(id)
    end

    def domain
        URI(url).host rescue URI::InvalidURIError
    end

    def editable_by?(user)
        user_id? && (user_id == user&.id)
    end

    def views_by_date_range(start_date, end_date)
        views.where(created_at: start_date..end_date)
    end

    private

    def url_exists
        return unless url.present?
    
        url = URI.parse(self.url)
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = (url.scheme == 'https')
    
        begin
          response = http.head(url.request_uri)
          unless response.code.to_i == 200 || response.code.to_i == 302
            errors.add(:url, "must be reachable (HTTP status #{response.code})")
          end
        rescue StandardError => e
          errors.add(:url, "could not be validated: #{e.message}")
        end
    end

    def url_format
        uri = URI.parse(url)
        return if uri.scheme.blank? || uri.host.blank?
      
        unless uri.scheme.start_with?("http")
            errors.add(:url, "must be HTTP or HTTPS")
        end

        if uri.host.end_with?(ENV['BASE_HOST'])
            errors.add(:url, "must not be from #{ENV['BASE_HOST']} or its subdomains")
        end
      rescue URI::InvalidURIError
        errors.add(:url, "is invalid")
    end   
end

app/models/metadata.rb
require "open-uri"

class Metadata
    attr_reader :doc

    def self.retrieve_from(url)
        new(URI.open(url))
    rescue new
    end

    def initialize(html = nil)
        @doc = Nokogiri::HTML(html)
    end

    def attributes
        {
            title: title,
            description: description,
            image: image
        }
    end

    def title
        doc.at_css("title")&.text || meta_tag_content("og:title")
    end

    def description
        meta_tag_content "description"
    end

    def image
        meta_tag_content "og:image", name_attribute: :property
    end

    def meta_tag_content(name, name_attribute: :name)
        doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
    end
end

app/models/short_code.rb
class ShortCode
    ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
    BASE = ALPHABET.length

    def self.encode(number)
        return ALPHABET.first if number.zero? || number.nil?

        result = ""

        while number > 0 do
            index = number % BASE
            char = ALPHABET[index]
            result.prepend char
            number = number / BASE
        end

        result
    end

    def self.decode(string)
        number = 0

        string.reverse.each_char.with_index do |char, index |
            power = BASE ** index
            index = ALPHABET.index(char)
            number += index * power
        end

        number
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
  scope :grouped_by_day, -> { group_by_day(:created_at).count }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

    def set_link
        @link = Link.find(params[:id])
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_action :set_link, only: [:show, :edit, :update, :destroy]
    before_action :check_if_editable, only: [:edit, :update, :destroy]

    def index
        @pagy, @links = pagy Link.recent_first
        @link ||= Link.new
    rescue Pagy::OverflowError
        redirect_to root_path
    end

    def show
    end

    def create
        @link = Link.new(link_params.with_defaults(user: current_user))
        if @link.save
            respond_to do |format|
                format.html { redirect_to root_path }
                format.turbo_stream { render turbo_stream: turbo_stream.prepend("links", @link) }
            end
        else
            index
            render :index, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @link.update(link_params)
            redirect_to @link
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @link.destroy
        redirect_to root_path, notice: "Link has been deleted."
    end

    def link_params
        params.require(:link).permit(:url)
    end

    def check_if_editable
        unless @link.editable_by?(current_user)
          redirect_to @link, alert: "You aren't allowed to do that."
        end
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    def index
      @links = Link.includes(:views).all
      @start_date = 1.month.ago.beginning_of_day
      @end_date = Time.current.end_of_day
    end
  end
  

app/controllers/views_controller.rb
class ViewsController < ApplicationController
    before_action :set_link

    rescue_from ActiveRecord::RecordNotFound do
        redirect_to root_path, alert: "Missing link!"
    end

    def show
        @link.views.create(
            ip: request.ip,
            user_agent: request.user_agent,
            geolocation: format_geolocation(request.env['ipinfo']),
            timestamp: Time.current
        )
        redirect_to @link.url, allow_other_host: true
    end
  
    def format_geolocation(data)
      return "unknown location" unless data
  
      city = data.city if data.respond_to?(:city)
      region = data.region if data.respond_to?(:region)
      country_name = data.country if data.respond_to?(:country)

      [city, region, country_name].compact.join(", ")
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/favicon_helper.rb
module FaviconHelper
    def favicon_image_tag(domain, **kwargs)
        image_tag google_favicon_url(domain), **kwargs
    end

    def google_favicon_url(domain)
        "https://www.google.com/s2/favicons?domain=#{domain}"
    end
end

app/views/about/index.html.erb
<div class="container mx-auto">
  <h1 class="text-2xl md:text-4xl font-extrabold mb-12">about snipIt.</h1>
  <p class="text-md md:text-lg pb-4 font-base">hey there, welcome to snipIt – where sharing just got a whole lot cooler!</p>
  <p class="text-md md:text-lg pb-4 font-base">snipIt is the ultimate tool for transforming those long, clunky URLs into short, snazzy links that are super easy to share. no more struggling with endless web addresses – just snip, snap, and share the url!</p>
  <p class="text-md md:text-lg pb-4 font-base">why snipIt, you ask? well, aside from being seriously awesome, snipIt is all about making your online life simpler and more fun. whether you're posting on social media, texting your crew, or sharing links with your squad, snipIt's got your back.</p>
  <p class="text-md md:text-lg pb-4 font-base">i poured my heart and soul into creating snipIt, so you know every link you create is gonna be as epic as you are. plus, it's seriously addictive – once you start snipping and sharing, you'll never wanna stop!</p>
  <p class="text-md md:text-lg pb-8 font-base">life's too short for boring URLs – let's snip, snap, and share our way to awesomeness with snipIt!</p>
  <p class="text-md md:text-lg mb-4 font-base">keep snipping and snapping,</p>
  <p class="text-md md:text-lg mb-4 font-base">ariessa.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>snipIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Snips long URLs into short URLs.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo.ico') %>
    <style>
        /* Hide the mobile menu by default */
        #mobile-menu {
            display: none;
        }
    </style>
  </head>

  <body class="flex flex-col h-screen">
    <header class="sticky top-0 z-50 bg-white border-b-2 border-black" data-controller="menu">
      <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
        <a href="/" class="-m-1.5 p-1.5 flex items-center justify-center">
          <span class="sr-only">snipIt</span>
          <%= image_tag("logo.svg", alt: "snipIt's logo", class: "h-6 w-6") %>
          <%= content_tag(:p, "snipIt", class: "font-semibold px-2") %>
        </a>
        <div class="flex lg:hidden">
          <button id="open-menu-button" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-900 hover:text-indigo-600" data-action="click->menu#openMenu">
            <span class="sr-only">Open main menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
        </div>
        <div class="hidden lg:flex lg:gap-x-12">
          <a href="/about" class="text-sm font-semibold leading-6 content-center text-gray-900 hover:text-indigo-600 hover:underline">about</a>
          <a href="/stats" class="text-sm font-semibold leading-6 content-center text-gray-900 hover:text-indigo-600 hover:underline">stats</a>
          <div class="hidden lg:flex lg:gap-x-4">
            <% if user_signed_in? %>
              <%= button_to "profile", edit_user_registration_path, class: "relative -ml-px inline-flex leading-6 items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white" %>
              <%= button_to "log out", destroy_user_session_path, method: :delete, class: "relative -ml-px inline-flex leading-6 items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-white ring-2 ring-inset ring-black bg-black hover:bg-white hover:text-indigo-600" %>
            <% else %>
              <%= button_to "login", new_user_session_path, class: "relative -ml-px inline-flex leading-6 items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white" %>
              <%= button_to "sign up", new_user_registration_path, class: "relative -ml-px inline-flex leading-6 items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-white ring-2 ring-inset ring-black bg-black hover:bg-white hover:text-indigo-600" %>
            <% end %>
          </div>
      </nav>
      <!-- Mobile menu, show/hide based on menu open state. -->
      <div id="mobile-menu" class="lg:hidden" role="dialog" aria-modal="true" data-menu-target="menu">
        <!-- Background backdrop, show/hide based on slide-over state. -->
        <div class="fixed inset-0 z-10"></div>
        <div class="fixed divide-y-2 divide-black inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-indigo-900/10">
          <div class="flex items-center justify-between">
            <a href="/" class="-m-1.5 p-1.5 flex items-center justify-center">
              <span class="sr-only">snipIt</span>
              <%= image_tag("logo.svg", alt: "snipIt's logo", class: "h-6 w-6") %>
              <%= content_tag(:p, "snipIt", class: "font-semibold px-2") %>
            </a>
            <button id="close-menu-button" type="button" class="-m-2.5 rounded-md p-2.5 text-gray-900 hover:text-indigo-600" data-action="click->menu#closeMenu">
              <span class="sr-only">Close menu</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="mt-6 flow-root">
            <div class="-my-6">
              <div class="flex flex-col pt-14 pb-8">
                <a href="/about" class="block px-3 py-2 text-base font-semibold leading-7 items-center text-gray-900 hover:bg-indigo-50 hover:text-indigo-600">about</a>
                <a href="/stats" class="block px-3 py-2 text-base font-semibold leading-7 items-center text-gray-900 hover:bg-indigo-50 hover:text-indigo-600">stats</a>
              </div>
              <div class="space-y-2">
                <div class="flex flex-col gap-y-4">
                <% if user_signed_in? %>
                  <%= button_to "profile", edit_user_registration_path, class: "block w-full leading-6 items-center px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white" %>
                  <%= button_to "log out", destroy_user_session_path, method: :delete, class: "block w-full leading-6 items-center px-3 py-2 text-sm font-semibold text-white ring-2 ring-inset ring-black bg-black hover:bg-indigo-600 hover:text-white" %>
                <% else %>
                  <%= button_to "login", new_user_session_path, class: "block w-full leading-6 items-center px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white" %>
                  <%= button_to "sign up", new_user_registration_path, class: "block w-full leading-6 items-center px-3 py-2 text-sm font-semibold text-white ring-2 ring-inset ring-black bg-black hover:bg-indigo-600 hover:text-white" %>
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <main class="prose mx-auto my-28 px-5 flex-1">
      <%= tag.p alert, class: "bg-yellow-100 text-yellow-800 text-sm font-medium px-4 py-2 rounded" if alert %>
      <%= tag.p notice, class: "bg-blue-100 text-blue-800 text-sm font-medium px-4 py-2 rounded" if notice %>
      <%= yield %>
    </main>

    <footer class="bg-white border-t-2 border-black py-6">
      <div class="mx-auto max-w-7xl px-6 flex items-center justify-center lg:px-8 gap-x-2">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="black" class="size-4 sm:size-6">
          <path d="m11.645 20.91-.007-.003-.022-.012a15.247 15.247 0 0 1-.383-.218 25.18 25.18 0 0 1-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0 1 12 5.052 5.5 5.5 0 0 1 16.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 0 1-4.244 3.17 15.247 15.247 0 0 1-.383.219l-.022.012-.007.004-.003.001a.752.752 0 0 1-.704 0l-.003-.001Z" />
        </svg>
        <p class="text-center font-semibold text-black text-xs sm:text-sm">crafted with love, a snip, and a snap by <a href="https://github.com/ariessa" target="_blank" rel="noopener noreferrer" class="underline hover:text-indigo-600 text-xs sm:text-sm">ariessa</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
    <%= turbo_stream_from link %>

    <div class="flex flex-col border-2 border-black p-4 gap-y-2 mb-4">
        <div class="flex flex-col pb-2">
            <div class="flex justify-between items-center">
                <%= tag.p "title", class: "text-xs font-normal" %>
                <%= link_to pluralize(link.views_count, "view"), link, class: "px-2 py-1 border-2 border-black no-underline text-xs hover:bg-indigo-600 hover:text-white" %>
            </div>
            <div class="flex w-full pt-1">
                <%= tag.p truncate(link.title), class: "border-2 border-black text-sm p-2 flex-1" %>
                <button class="relative -ml-px inline-flex items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white"
                    data-controller="clipboard" data-clipboard-text="<%= link.title %>">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                        <path d="M7.5 3.375c0-1.036.84-1.875 1.875-1.875h.375a3.75 3.75 0 0 1 3.75 3.75v1.875C13.5 8.161 14.34 9 15.375 9h1.875A3.75 3.75 0 0 1 21 12.75v3.375C21 17.16 20.16 18 19.125 18h-9.75A1.875 1.875 0 0 1 7.5 16.125V3.375Z" />
                        <path d="M15 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 17.25 7.5h-1.875A.375.375 0 0 1 15 7.125V5.25ZM4.875 6H6v10.125A3.375 3.375 0 0 0 9.375 19.5H16.5v1.125c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 0 1 3 20.625V7.875C3 6.839 3.84 6 4.875 6Z" />
                    </svg>
                </button>
            </div>
        </div>

        <div class="flex flex-col pb-2">
            <%= tag.p "short url", class: "text-xs font-normal" %>
            <div class="flex w-full pt-1">
                <%= tag.p truncate(view_url(link)), class: "border-2 border-black text-sm p-2 flex-1" %>
                <button class="relative -ml-px inline-flex items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white"
                    data-controller="clipboard" data-clipboard-text="<%= view_url(link) %>">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                        <path d="M7.5 3.375c0-1.036.84-1.875 1.875-1.875h.375a3.75 3.75 0 0 1 3.75 3.75v1.875C13.5 8.161 14.34 9 15.375 9h1.875A3.75 3.75 0 0 1 21 12.75v3.375C21 17.16 20.16 18 19.125 18h-9.75A1.875 1.875 0 0 1 7.5 16.125V3.375Z" />
                        <path d="M15 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 17.25 7.5h-1.875A.375.375 0 0 1 15 7.125V5.25ZM4.875 6H6v10.125A3.375 3.375 0 0 0 9.375 19.5H16.5v1.125c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 0 1 3 20.625V7.875C3 6.839 3.84 6 4.875 6Z" />
                    </svg>
                </button>
            </div>
        </div>

        <div class="flex flex-col">
            <%= tag.p "long url", class: "text-xs font-normal" %>
            <div class="flex w-full pt-1">
                <%= tag.p truncate(link.url), class: "border-2 border-black text-sm p-2 flex-1" %>
                <button class="relative -ml-px inline-flex items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white"
                    data-controller="clipboard" data-clipboard-text="<%= link.url %>">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                        <path d="M7.5 3.375c0-1.036.84-1.875 1.875-1.875h.375a3.75 3.75 0 0 1 3.75 3.75v1.875C13.5 8.161 14.34 9 15.375 9h1.875A3.75 3.75 0 0 1 21 12.75v3.375C21 17.16 20.16 18 19.125 18h-9.75A1.875 1.875 0 0 1 7.5 16.125V3.375Z" />
                        <path d="M15 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 17.25 7.5h-1.875A.375.375 0 0 1 15 7.125V5.25ZM4.875 6H6v10.125A3.375 3.375 0 0 0 9.375 19.5H16.5v1.125c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 0 1 3 20.625V7.875C3 6.839 3.84 6 4.875 6Z" />
                    </svg>
                </button>
            </div>
        </div>
        </div>
    </div>
<% end%>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="flex mt-4 gap-1 items-center">
    <%= link_to "Cancel", @link, class: "hover:text-indigo-600" %>
    or
    <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "hover:text-indigo-600" %>
</div>

app/views/links/index.html.erb
<div class="w-full items-center">
  <h1 class="w-full text-center">snip. snap. share.</h1>

  <%= render partial: "form", locals: {link: @link} %>

  <div id="links" class="mt-8 flex flex-col">
    <%= render @links %>

    <% if @pagy.pages > 1 %>
      <div class="pt-8 mb-16 text-center">
        <%== pagy_nav @pagy %>
      </div>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<div class="flex justify-between items-center text-xs">
    <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 border-2 font-semibold text-gray-900 border-black hover:bg-indigo-600 hover:text-white" %>
    <div class="flex items-center gap-4">
        <%= tag.div pluralize(@link.views_count, "view"), class: "font-semibold" %>
        <button class="relative -ml-px inline-flex items-center gap-x-1.5 px-3 py-2 text-sm font-semibold text-gray-900 ring-2 ring-inset ring-black hover:bg-indigo-600 hover:text-white"
            data-controller="clipboard" data-clipboard-text="<%= view_url(@link) %>">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
                <path d="M7.5 3.375c0-1.036.84-1.875 1.875-1.875h.375a3.75 3.75 0 0 1 3.75 3.75v1.875C13.5 8.161 14.34 9 15.375 9h1.875A3.75 3.75 0 0 1 21 12.75v3.375C21 17.16 20.16 18 19.125 18h-9.75A1.875 1.875 0 0 1 7.5 16.125V3.375Z" />
                <path d="M15 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 17.25 7.5h-1.875A.375.375 0 0 1 15 7.125V5.25ZM4.875 6H6v10.125A3.375 3.375 0 0 0 9.375 19.5H16.5v1.125c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 0 1 3 20.625V7.875C3 6.839 3.84 6 4.875 6Z" />
            </svg>
        </button>
        <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-1.5 border-2 border-black no-underline hover:bg-indigo-600 hover:text-white" if @link.editable_by?(current_user) %>
    </div>
</div>

<h1 class="mt-4"><%= @link.title %></h1>
<%= tag.div @link.description %>

<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-1.5 border-2 border-black no-underline hover:bg-indigo-600 hover:text-white" do %>
    <%= favicon_image_tag @link.domain, class: "inline-block" %>
    <%= truncate @link.url %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 inline-block">
        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
<% end %>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count, colors: ["#4f46e5"] %>

<% if @link.views_count > 0 %>
    <div class="pt-4 gap-y-4">
        <h2 class="text-lg font-semibold">All Views</h2>
        <% @link.views.each do |view| %>
            <div class="flex flex-col border-2 border-black p-4 gap-y-2 mb-4">
                <div class="flex flex gap-x-2 justify-between items-center">
                    <%= tag.p "ip address", class: "text-xs font-semibold" %>
                    <%= tag.p view.ip, class: "text-xs font-base" %>
                </div>
                <div class="flex flex gap-x-2 justify-between items-center">
                    <%= tag.p "geolocation", class: "text-xs font-semibold" %>
                    <%= tag.p view.geolocation, class: "text-xs font-base" %>
                </div>
                <div class="flex flex gap-x-2 justify-between items-center">
                    <%= tag.p "timestamp", class: "text-xs font-semibold" %>
                    <%= tag.p view.timestamp, class: "text-xs font-base" %>
                </div>
            </div>
        <% end %>
    </div>
<% end %>